name: Deploy RG and Storage Account

on:
  push:
    branches:
      - deploy-storage-workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          auth-type: SERVICE_PRINCIPAL

      - name: Deploy Subscription-Level Bicep Template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}
          scope: subscription
          region: eastus  
          template: ./main.bicep  
          parameters: |
            storageAccountName=namanuniquestorage123
            location=eastus
            resourceGroupName=myRG
          deploymentName: github-subscription-deploy
          deploymentMode: Incremental