name: Deploy Storage Workflow

on:
  push:
    branches:
      - deploy-storage-workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure using service principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: false
        environment: azurecloud
        allow-no-subscriptions: false
        audience: api://AzureADTokenExchange
        auth-type: SERVICE_PRINCIPAL

    - name: Deploy Bicep template using Azure ARM Deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: eastus
        template: ./main.bicep
        parameters: ./parameters.json